### ISSUE TITLE
Compile error with base-4.8

### ISSUE THREAD

**Issue by hvr** [esoeylemez/rapid-term#1]
The cabal file specifies compatibility with `base >= 4.8`, however GHC 7.10 disagrees:

```
Configuring component lib from rapid-term-0.1.0
Preprocessing library rapid-term-0.1.0...

src/Rapid/Term.hs:50:8:
    Could not find module ‘Control.Monad.IO.Class’
    It is a member of the hidden package ‘transformers-0.5.2.0@9bQiiqEjk1m49Kq789uTsg’.
    Perhaps you need to add ‘transformers’ to the build-depends in your .cabal file.
    It is a member of the hidden package ‘transformers-0.4.2.0@trans_GZTjP9K5WFq01xC9BAGQpF’.
    Perhaps you need to add ‘transformers’ to the build-depends in your .cabal file.
    Use -v to see a list of the files searched for.
```

**Comment by hvr** [comment]
Btw, I notice you have SemVer-style upper bounds in place for packages which follow [PVP](http://pvp.haskell.org/)-style semantics:

```
        ansi-terminal >= 0.6 && < 1,
        base >= 4.8 && < 5,
        clock >= 0.7 && < 1,
        kan-extensions >= 5.0 && < 6,
        process >= 1.4 && < 2,
        unix >= 2.7 && < 3
```

Is this deliberate?

**Comment by esoeylemez** [comment]
Thanks for your report! Fixed and tested with GHC 7.10 and GHC 8.

The version bounds are deliberate based on the experience that the maintenance cost of fixing breakage is far lower than the cost of keeping up with minor versions. In fact such breakage has only occurred once for me in years. However, I do follow PVP in my version numbers.

**Comment by hvr** [comment]
@esoeylemez fair enough (btw, are you talking about breakage due to type-level changes or semantic changes?), but then I'm confused a bit why you set upper bounds at all

As the maintainer of `unix` I can say that I'm trying to avoid a major version increments until it's no longer avoidable (and one such major reason is semantic changes which are not visible at the type-level, so stuff will keep compiling, but it may behave surprisingly different/incorrectly); but I'm now worrying that people won't notice the major-version bump signal if they don't set the proper major-version upper bounds. :-/

**Comment by esoeylemez** [comment]
@hvr: That's basically my assumption: A semantic change should come along with a major version bump. That is also the reason why I set upper bounds the way I do. Of course if feedback indicates that I should follow the PVP more closely with my dependency bounds, I don't mind doing it too much.

What's your view on this?

**Comment by hvr** [comment]
@esoeylemez well, you set a bound `unix < 3`, and `unix` is currently at `unix-2.7.2.1`; the next major version bumped release (which may contain semantic changes) is going to result in version `unix-2.8.0`. However, since `2.8.0 < 3`, that upper bound won't make you notice that signal and so there's a real chance you may miss that `unix` contained semantic changes which (may) affect the correctness of your package.

**Comment by esoeylemez** [comment]
That's convincing. I will update the bounds.
